flowchart TD
    U[User] --> |inputs| Q(Query)
    Q --> TQ{Is travel related?}
    TQ --> |no| RR[Regret Response]
    TQ --> |yes| UQ{Is user related?}
    UQ --> |yes| RU(Rewrite user query) 
    RU --> UR(fetch user data)
    UQ --> |no| N{Is new query?}
    UR --> N
    N --> |yes| RT(Rewrite travel query)
    RT --> NT(fetch travel guides)
    NT --> |use guides only| C[LLM completion]
    N --> |no| OT(fetch history)
    OT --> |use history only| C
    C --> TR{Answers user?}
    TR --> |yes| OR(Output Response)
    TR --> |no| RR
    RR --> |retry| U
    OR --> S[Save history]
    S --> |more?| U
